name: CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    env:
      FC: gfortran

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install GFortran macOS
      if: contains(matrix.os, 'macos')
      run: |
          ln -s /usr/local/bin/gfortran-9 /usr/local/bin/gfortran
          which gfortran-9
          which gfortran

    - name: Build and test (Windows)
      if: contains(matrix.os, 'windows')
      run: |
          ci\citest.bat

    - name: Build and test (Linux / macOS)
      if: contains(matrix.os, 'ubuntu') || contains(matrix.os, 'macos')
      run: |
          bash ci/citest.sh
